package com.advancedcomponentservices.acswarehouse.db.models

import java.util.Date

data class Orders(
    val lineItemId: String,
    val id: String,
    val po: String,
    val date: Date,
    val nameZip: String,
    val namePhone: String,
    val nameEmail: String,
    val shipDate: Date,
    val via: String,
    val terms: String,
    val num: String,
    val name: String,
    val qty: Number,
    val upsAccount: String,
    val item: String,
    val itemDescription: String,
    val backOrdered: Int,
    val shipToCity: String,
    val shipToAddress: String,
    val shipToAddress2: String,
    val shipToState: String,
    val shipToZip: String,
    val binLocation: String,
    val shipToDateIs7DaysFromToday: Boolean,
    val onHand: Int,
    val onPurchaseOrder: Int,
    val purchaseOrder: Int,
    val matchedPo: String,
    val expectedDate: Date,
    val noteCode: String,
    val reviewDate: Date,
    val note: String,
    val sendToWarehouse: Boolean,
    val partial: Boolean,
    val hasException: Boolean,
    val orderCt: String,
    val matchDataForLabelCheck: String,
    val baseSku: String,
    val packQty: String,
    val requiredQty: String,
    val invoiced: Boolean,
    val isKit: Boolean,
    val shippedQty: Int,
    val bulkBinLocation: String
)
